### ISSUE TITLE
vscode-clang-format-provider conflicts with redhat.java when formating java code

### ISSUE THREAD

**Issue by gujunhk** [xaverh/vscode-clang-format-provider#35]
After installing the extension *Language Support for Java(TM) by Red Hat*, vscode can't format java code anymore.
Could I format java code with clang-format instead of redhat-java?
Or could you add a new command like "Format Code with Clang-Format"?

**Comment by xaverh** [comment]
I am not a huge fan of including a command the bypasses the official formatter API for the following reasons:
- It would not (or at least not easily) be able to use the features that come with the official API like "format on save" and "format selection"
- It would need a manual keybinding (which either is different from the original one or basically disables formatting for everything not covered by this extension)
- It would clutter the menu for all users of this extension with an additional (probably worse) command which will cause confusion
This issue has emerged with C++ and TypeScript before: https://github.com/Microsoft/vscode/issues/11609
The fix was that the Microsoft C/C++ extension included an option to disable their formatter. Similarly, this extension included options to disable itself for selected languages because some users wanted it to not format their TypeScript, etc.
This seems to be the way forward for Java as well.

**Comment by xaverh** [comment]
see https://github.com/redhat-developer/vscode-java/issues/186
