### ISSUE TITLE
Format all files in a folder

### ISSUE THREAD

**Issue by devnoname120** [xaverh/vscode-clang-format-provider#40]
I would like to format all the files in a specific folder, without opening each file individually.

How should I proceed?

**Comment by xaverh** [comment]
The extension does not provide a command for formatting all the files in one folder since VS Code does not provide that feature in the API (as far as I know). The easiest way would be to write a task that does that for you.
Like
```json
{
    "version": "0.1.0",
    "tasks": [
        {
            "taskName": "clang-format-everything",
            "command": "clang-format",
            "args": ["-i", "*" ],
            "isShellCommand": true,
            "isBackground": true
        }
    ]
}
```
in your `tasks.json`.
Then, you could also assign a keybinding in `keybindings.json`:
```json
{
    "key": "ctrl+h",
    "command": "workbench.action.tasks.runTask",
    "args": "clang-format-everything"
}
```
(cf. https://code.visualstudio.com/docs/editor/tasks).
