### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by dingwd** [xaverh/vscode-clang-format-provider#48]
The 'clang-format' command is not available. Please check your clang-format.executable user setting and ensure it is installed.

**Comment by xaverh** [comment]
Which version of clang-format do you have? And what did you set `"clang-format.executable"` to?
This bug report is not very helpful...

**Comment by dingwd** [comment]
Visual Studio Code  Version 1.13.0
Clang-Format 1.5.0
![b x8 d 0l jhyfciuz4d](https://user-images.githubusercontent.com/14259020/27160563-bdbfa2f8-51a7-11e7-937e-3fcbbc5f8eb7.png)

**Comment by xaverh** [comment]
This error message gets thrown at https://github.com/xaverh/vscode-clang-format-provider/blob/master/src/extension.ts#L187. It ususally appears when the clang-format extension cannot find clang-format.
It requires clang-format by LLVM in order to work. You can either download it from http://llvm.org or install it via `npm install -g clang-format` or through a package manager (apt, pacman, brew, nuget, dnf).
Also make sure the binary is in your $PATH (cf. README) or manually given to the extension in the `"clang-format.executable"` setting in your `settings.json`.

**Comment by Qu1ckZ** [comment]
@xaverh Thx!
I updated it using "sudo npm i -g npm" and now it works perfectly.

**Comment by ilyashamd** [comment]
`sudo apt-get install clang-format` in Linux also solves the problem!

**Comment by MichaelCxc** [comment]
I also met the problem on mac.
If you directly input `npm install -g clang-format` in Mac terminal, it cannot be fixed.
Please input this command in your visual studio terminal, not original mac terminal

**Comment by meteorsh** [comment]
In mac, `sudo npm install -g clang-format` solves the problem!

**Comment by tlaak** [comment]
On a Mac, if you have Homebrew, you can also say `brew install clang-format` to install it globally.

**Comment by JannikWimmer** [comment]
Solution for Windows: 
https://llvm.org/builds/

At the bottom of this page you can download only the clang-format plugin for VS Code. 

Drag the unzipped folder into C: / and add it to PATH.

**Comment by Daosole** [comment]
On Fedora, just use `sudo dnf install clang-tools-extra`  to install clang-format.

**Comment by siam116** [comment]
`sudo apt-get install clang-format` works fine for Mac as well. Thanks @ilyashamd

**Comment by yulongshan** [comment]
> `sudo apt-get install clang-format` in Linux also solves the problem!
